# 도커 컴포즈 :
# 여러개의 도커 컨테이너들을 하나의 서비스로 정의하고 구성해 "하나의 묶음"으로 관리할 수 있게 도와주는 툴

# 컨테이너를 한개 한개씩 띄움
# 여러개를 동시에 띄워야 하는 경우가 많음.
# spring boot, mysql, next.js 여러개를 띄우는 경우가 많음
# 여러 컨테이너를 하나의 묶음으로 관리할 수 있게 해주는게 "도커 컴포즈"

# 도커 컴포즈 사용 하는 이유
# 1. 여러개의 컨테이너를 관리하는데 용이
#    여러개의 컨테이너로 이루어진 복잡한 애플리케이션을 한 파일로 관리하는데 도움을 줌

# 2. 복잡한 명령어로 실행시키던걸 간소화할 수 있음

# 아래처럼 작성 된 명령어가 컴포즈 파일 문법에 맞게 작성한거
# docker run --name web-server -d -p 80:80 nginx
services:
  my-web-server:
    container_name: web-server
    image: nginx
    ports:
      - 80:80