services:
  spring-boot-server:
    # image: 원래는 이미지를 사용을 했는데 이미지를 이제 도커파일을 기반으로 한 빌드 된 이미지를 사용을 하겟다는거다
    build: .  # 경로는 도커 파일이 위치한 경로를 작성을 하면 되고 경로는 상대 경로임 기준은 compose.yml 기준으로 도커파일 위치 하면 . 함녀 됨
    ports:
      - 8080:8080